79 update config README
nestauk/asf_heat_pump_suitability pull request #91
Opened 2024-12-04 18:33 UTC by crispy-wonton

Fixes #79 

# Description

Add new data sources and attributions to config/README

# Instructions for Reviewer

During your review, along with general review of readability /clarity etc, please could you check:
- all links work and take you to the expected dataset
- descriptions make sense
- you agree with removing the `S3 file` column. I removed it because I don't think it added value as all the S3 paths can already be found in the `config/base.yaml` and also because they are so changeable it would create unnecessary work to maintain the README.
- all the appropriate data attribution statements are there

# Checklist:

- [ ] I have refactored my code out from `notebooks/`
- [ ] I have checked the code runs
- [ ] I have tested the code
- [ ] I have run `pre-commit` and addressed any issues not automatically fixed
- [ ] I have merged any new changes from `dev`
- [ ] I have documented the code
  - [ ] Major functions have docstrings
  - [ ] Appropriate information has been added to `README`s
- [ ] I have explained this PR above
- [ ] I have requested a code review

2025-01-08 09:19 UTC, caldwellst requested changes
My first review! Overall makes sense, and looks much cleaner than before!

However, might want to add a bit more detail on the storage and updating of the data, as that wasn't clear to me from reviewing this or searching through the repo initially (admittedly I didn't search for too long!). There's a few links I've highlighted that are dead or possibly incorrect.

Other than that, the one I did notice, which would likely just need y'alls discussion outside this PR, is a dataset that seems to have updated end of November that you may want to update in the pipeline.

2025-01-08 09:19 UTC, caldwellst commented on asf_heat_pump_suitability/config/README.md
> +| In building conservation area | `["W_welsh_gov_conservation_areas"]`                       | [Welsh Government](https://datamap.gov.wales/layers/inspire-wg:conservation_areas)<sup>4</sup>
Beyond the scope of this PR, but just to note that the conservation areas you linked have now been flagged as `(old)` and there's a new dataset from November 28 2024 [here](https://datamap.gov.wales/layers/geonode:conservation_areas_wales)!

2025-01-08 09:19 UTC, caldwellst commented on asf_heat_pump_suitability/config/README.md
> +key used in `asf_heat_pump_suitability/config/base.yaml` under the primary `["data_source"]` key.
General note possibly outside this PR, but may want to consider instead of `Date` using `Date of access`? I assume most of these assets are static on S3 and not updated every run from source? Just a slightly more standard convention that also can be easier to maintain since you only update the date when you update your codebase/database. Not critical though.

2025-01-08 09:19 UTC, caldwellst commented on asf_heat_pump_suitability/config/README.md
> +| Grid capacity                 | `["UK_poi_locations"]`                                     | [CDRC](https://data.cdrc.ac.uk/dataset/point-interest-data-united-kingdom)<sup>3</sup>
lol "Site under maintenance". Will check back, but assume has nothing to do with the underlying data. Leaving this flag for myself.

2025-01-08 09:19 UTC, caldwellst commented on asf_heat_pump_suitability/config/README.md
> +| Grid capacity                 | `["EW_WPD_capacity"]`                                      | [WPD Network Capacity Map](https://connecteddata.nationalgrid.co.uk/dataset/nged-network-capacity/resour
Hmm, 403 error forbidden. So might be valid, just I don't have access!

2025-01-08 09:19 UTC, caldwellst commented on asf_heat_pump_suitability/config/README.md
> +| Grid capacity                 | `["EW_WPD_capacity"]`                                      | [WPD Network Capacity Map](https://connecteddata.nationalgrid.co.uk/dataset/nged-network-capacity/resour
Probably why the links below are to the general "Spatial datasets" page.

2025-01-08 09:19 UTC, caldwellst commented on asf_heat_pump_suitability/config/README.md
> +|     `["EW_cdrc_dwelling_age"]`     | [CDRC](https://data.cdrc.ac.uk/dataset/dwelling-ages-and-prices/resource/dwelling-age-band-counts-lsoa-2015)<sup>11</sup>
Hmm, dataset doesn't seem to load, says "The file could not be created" and searching for "dwelling" doesn't return anything immediately.

2025-01-08 09:19 UTC, caldwellst commented on asf_heat_pump_suitability/config/README.md
> +This table shows the different datasets used to calculate each feature and their sources. The 'Config key' column indicates the
Where's this data stored? How is it updated? Are they static files updated only when we select, or are they updated in every pipeline run? I see where this doc is linked on the main README, but no real mention there, and some mention of EPC data coming from asf-daps in the pipeline README, but unclear here.

2025-01-08 17:02 UTC, crispy-wonton commented on asf_heat_pump_suitability/config/README.md
> +| In building conservation area | `["W_welsh_gov_conservation_areas"]`                       | [Welsh Government](https://datamap.gov.wales/layers/inspire-wg:conservation_areas)<sup>4</sup>
Great flag, thank you!

2025-01-08 17:03 UTC, crispy-wonton commented on asf_heat_pump_suitability/config/README.md
> +| In building conservation area | `["W_welsh_gov_conservation_areas"]`                       | [Welsh Government](https://datamap.gov.wales/layers/inspire-wg:conservation_areas)<sup>4</sup>
Have added to sprint backlog.

2025-01-08 17:05 UTC, crispy-wonton commented on asf_heat_pump_suitability/config/README.md
> +This table shows the different datasets used to calculate each feature and their sources. The 'Config key' column indicates the
Good points, thank you. I'll add this information.

2025-01-08 17:44 UTC, crispy-wonton commented on asf_heat_pump_suitability/config/README.md
> +|     `["EW_cdrc_dwelling_age"]`     | [CDRC](https://data.cdrc.ac.uk/dataset/dwelling-ages-and-prices/resource/dwelling-age-band-counts-lsoa-2015)<sup>11</sup>
Thanks! looks like they updated the path slightly

2025-01-08 17:47 UTC, crispy-wonton commented on asf_heat_pump_suitability/config/README.md
> +| Grid capacity                 | `["UK_poi_locations"]`                                     | [CDRC](https://data.cdrc.ac.uk/dataset/point-interest-data-united-kingdom)<sup>3</sup>
Is this the POI dataset? If so, seems to be working now: https://data.cdrc.ac.uk/dataset/point-interest-data-united-kingdom

2025-01-08 18:50 UTC, caldwellst commented on asf_heat_pump_suitability/config/README.md
> +| Grid capacity                 | `["UK_poi_locations"]`                                     | [CDRC](https://data.cdrc.ac.uk/dataset/point-interest-data-united-kingdom)<sup>3</sup>
Yep, all good now!

2025-01-10 17:49 UTC, crispy-wonton commented on asf_heat_pump_suitability/config/README.md
> +key used in `asf_heat_pump_suitability/config/base.yaml` under the primary `["data_source"]` key.
I think it's a good idea for us to include date of access. Will do this in a separate PR.

I think we should also keep the date of the dataset itself so that we can easily see how old the data is that we're using.

2025-01-10 18:09 UTC, crispy-wonton commented
@caldwellst I've addressed/responded to your comments. Since your last review I have:

1. Added info on how the datasets are stored and update
2. Added info on where the EPC data comes from and licensing
3. Missing data attribution/licensing statements for grid capacity datasets
4. 2 new grid capacity datasets: 'S_SSEN_demand' and 'SHET_SSEN_demand' config keys
5. Replaced broken/forbidden links 
6. I have checked all the links work

Please let me know if you are happy with the changes, especially 1 and 2.

2025-01-13 10:04 UTC, caldwellst approved these changes, later dismissed
All looks good now!

2025-01-13 10:58 UTC, lizgzil approved these changes, later dismissed
@crispy-wonton I've read through the descriptions, checked against the config, and this looks great to me and makes sense to remove the s3 path. I'm not aware that you've missed anything. Thanks for being so thorough! 🎉

2025-01-13 10:58 UTC, lizgzil commented on asf_heat_pump_suitability/config/README.md
> +| LSOA, MSOA, LAD               | `["UK_ons_postcode_dir"]`                                  | [ONS](https://geoportal.statistics.gov.uk/datasets/487a5ba62c8b4da08f01eb3c08e304f6/about)<sup>1,2,3</su
```suggestion
| LSOA, MSOA, LAD, RUC               | `["UK_ons_postcode_dir"]`                                  | [ONS](https://geoportal.statistics.gov.uk/datasets/487a5ba62c8b4da08f01eb3c08e304f6/about)<sup>1,2,3</sup>                                                                                                                                                                 | August 2023                       | ONS postcode directory for UK as at August 2023. Source of output area information and rural-urban classification<sup>a</sup>. |
```

2025-01-13 11:06 UTC, merged